#!/bin/sh
# start xorg

# launch pipewire for audio
echo 'launching pipewire...'
pipewire >$HOME/.logs/pipewire.log 2>&1 &
pipewire-pulse >$HOME/.logs/pipewire-pulse.log 2>&1 &
wireplumber >$HOME/.logs/wireplumber.log 2>&1 &

# launch X and redirect the startx output to $HOME/.xorg.log
echo 'starting X...'
startx -- /usr/local/bin/X vt1 -keeptty >$HOME/.logs/xorg.log 2>&1

# once we exited out of X, also quit out of pipewire
echo 'terminating pipewire...'
pkill wireplumber
pkill pipewire
pkill pipewire-pulse
